<html>
<head>
<title>ViV</title>
<link rel="stylesheet" type="text/css" href="/css/base.css" />
<!-- Required CSS -->
<link type="text/css" rel="stylesheet" href="http://yui.yahooapis.com/2.8.1/build/treeview/assets/skins/sam/treeview.css">
<!-- Optional CSS for for date editing with Calendar-->
<link type="text/css" rel="stylesheet" href="http://yui.yahooapis.com/2.8.1/build/calendar/assets/skins/sam/calendar.css">

<!-- Dependency source file --> 
<script src="http://yui.yahooapis.com/2.8.1/build/yahoo-dom-event/yahoo-dom-event.js" ></script>
<!-- Optional dependency source file --> 
<script src="http://yui.yahooapis.com/2.8.1/build/animation/animation-min.js" type="text/javascript"></script>
<!-- Optional dependency source file for date editing with Calendar--> 
<script src="http://yui.yahooapis.com/2.8.1/build/calendar/calendar-min.js" ></script>
<!-- Optional dependency source file to decode contents of yuiConfig markup attribute--> 
<script src="http://yui.yahooapis.com/2.8.1/build/json/json-min.js" ></script>

<!-- TreeView source file --> 
<script src="http://yui.yahooapis.com/2.8.1/build/treeview/treeview-min.js" ></script>

</head>
<body class="yui-skin-sam">
<div id="header">
<h1><a href="/">ViV</a></h1>
</div>
[% INCLUDE navi.inc %]
<div id="container">
